import { beforeEach, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ tenant: { findUnique: vi.fn() }, appointment: { findFirst: vi.fn() }, cfg: vi.fn(), agenda: vi.fn(), send: vi.fn(), local: vi.fn(), product: vi.fn(), session: vi.fn() }));
vi.mock("@/lib/prisma", () => ({ prisma: mocks }));
vi.mock("@/lib/session", () => ({ requireTenant: mocks.session }));
vi.mock("@/lib/require-product", () => ({ requireProductAccess: mocks.product }));
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
vi.mock("@/modules/scheduling/clinicorp", () => ({ listClinicorpAgenda: mocks.agenda }));
vi.mock("../workers/follow-up-worker/reminders", () => ({ loadAccountScheduleConfigs: mocks.cfg, scanAndSendReminders: mocks.local }));
vi.mock("../workers/follow-up-worker/clinicorp-reminders", () => ({ sendClinicorpConfirmation: mocks.send }));
import { appointmentConfirmationAction } from "../src/app/(dashboard)/agenda/confirmation-actions";
import { parseScheduleConfig } from "@/modules/scheduling/config";
const form = () => { const f = new FormData(); f.set("id", "123"); f.set("source", "clinicorp"); f.set("startsAt", "2030-01-01T15:00:00.000Z"); f.set("operation", "send"); f.set("tenantId", "attacker"); return f; };
beforeEach(() => { vi.clearAllMocks(); mocks.product.mockResolvedValue(undefined); mocks.session.mockResolvedValue({ tenantId: "owner", session: { user: { id: "u" } } }); mocks.tenant.findUnique.mockResolvedValue({ status: "active" }); mocks.cfg.mockResolvedValue(new Map([["owner", parseScheduleConfig({ reminderEnabled: true })]])); mocks.agenda.mockResolvedValue({ status: "ok", items: [{ id: "123", startsAt: new Date("2030-01-01T15:00:00Z") }] }); mocks.appointment.findFirst.mockResolvedValue(null); mocks.send.mockResolvedValue({ sent: true, reason: "sent" }); });
it("usa tenant da sessão, não o do formulário", async () => { expect((await appointmentConfirmationAction(null, form())).ok).toBe(true); expect(mocks.send.mock.calls[0][0]).toBe("owner"); });
it("conta suspensa não lê agenda nem envia", async () => { mocks.tenant.findUnique.mockResolvedValue({ status: "suspended" }); expect((await appointmentConfirmationAction(null, form())).ok).toBe(false); expect(mocks.agenda).not.toHaveBeenCalled(); });
it("produto recusado não chega ao envio", async () => { mocks.product.mockRejectedValue(new Error("denied")); await expect(appointmentConfirmationAction(null, form())).rejects.toThrow(); expect(mocks.send).not.toHaveBeenCalled(); });
it("consulta fora do tenant não envia", async () => { mocks.agenda.mockResolvedValue({ status: "ok", items: [] }); expect((await appointmentConfirmationAction(null, form())).ok).toBe(false); expect(mocks.send).not.toHaveBeenCalled(); });
it("horário antigo após remarcação não envia", async () => { mocks.agenda.mockResolvedValue({ status: "ok", items: [{ id: "123", startsAt: new Date("2030-01-02T15:00:00Z") }] }); expect((await appointmentConfirmationAction(null, form())).ok).toBe(false); expect(mocks.send).not.toHaveBeenCalled(); });
it("manual usa mesmo serviço e registra usuário", async () => { const f = form(); f.set("operation", "manual"); mocks.send.mockResolvedValue({ sent: false, reason: "manual" }); expect((await appointmentConfirmationAction(null, f)).ok).toBe(true); expect(mocks.send.mock.calls[0][3]).toMatchObject({ operation: "manual", userId: "u" }); });
it("resultado incerto não informa sucesso", async () => { mocks.send.mockResolvedValue({ sent: false, reason: "unknown" }); expect((await appointmentConfirmationAction(null, form())).ok).toBe(false); });
